### PR TITLE
Added map emoji to the list

### PR DESCRIPTION
**Pull request by nikivdev**
I often use this 🗺️ and this amazing workflow didn't have it.

I hope this works.

Also can't edit my workflow locally as for some reason instead of emojis and unicode I get these values : 

2017-04-21 at 15 10

### CODE REVIEW

**Comment by bevesce** [comment]
Maybe I'm missing something but the map emoji is on the list as "world map".

And I don't understand what do you mean by second comment, sorry. What values?

**Comment by nikivdev** [comment]
When I type 'world map' in the workflow nothing happens : 

2017-04-21 at 17 07

And these values are what I see when I go to alfred directory with the workflow and open .txt file. It seems different to this repository.

**Comment by bevesce** [comment]
It sounds like you are not using newest version of this workflow

**Comment by nikivdev** [comment]
Just updated and checked it again and you are right. :)

However why do these values show in the results : 

2017-04-21 at 17 29

Like the value '00015f..' in the subscript. I didn't have it in the previous version and it is quite annoying. :(

**Comment by bevesce** [comment]
It's symbol unicode value, [somebody else asked me to include this in a description](https://github.com/bevesce/unicode-symbols-search/issues/9). I guess you can't please everybody :(

**Pull request closed without merging**
